[package]
name = "cens-r/switchcase"
description = "Luau switchcase implementation!"

authors = ["Cens-r"]
version = "2.0.0"
license = "MIT"

registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

include = ["src", "src/**", "default.project.json", "wally.toml"]
exclude = ["**"]

[dependencies]
