[package]
name = "cens-r/SwitchCase"
description = "Luau Switch-Case Implementation"
license = "MIT"
authors = ["Censor"]
version = "1.0.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = [".gitattributes", ".gitignore", "SwitchCase.rbxm", "selene.toml"]

[dependencies]
